trigger:
  branches:
    include:
      - main

pool:
  name: 'Azure Linux VM'

variables:
  repository: 'mxinfo.configuration.db'
  imageName: 'mxinfo.azurecr.io/mxinfo.configuration.db'
  tag: '$(build.buildId)'

steps:
  - script: |
      chmod +x ./generate-local-image.sh
      ./generate-local-image.sh -s $SA_PASSWORD -a $APP_PASSWORD -i $(imageName) -t $(tag)
    displayName: 'Build database image'
    env:
      SA_PASSWORD: $(SAPASSWORD)
      APP_PASSWORD: $(APPPASSWORD)

  - task: Docker@2
    displayName: 'Push Docker Image'
    inputs:
      containerRegistry: 'mxinfo-container-registry'
      repository: '$(repository)'
      command: 'push'
      container: $(imageName):$(tag)

  - task: Docker@2
    displayName: 'Remove Local Docker Image'
    inputs:
      command: 'rmi'
      arguments: $(imageName):$(tag)
